brew "awscli"
brew "gemini-cli"
brew "gh"
brew "git"
brew "go"

cask "1password"
cask "claude-code"
cask "discord"
cask "font-fira-code"
cask "ghostty"
cask "github"
cask "google-chrome"
cask "signal"
cask "visual-studio-code"
cask "whatsapp"
